const BASE = "https://learn.nextwork.org/courses/static";

export const CATEGORY_IMAGES: Record<string, string> = {
  "All":                              `${BASE}/plane-isle.webp`,
  "New":                              `${BASE}/forest.webp`,
  "AI Second Brain":                  `${BASE}/pyramid.webp`,
  "Git & Github":                     `${BASE}/github.webp`,
  "Claude Roadmap":                   `${BASE}/claude-roadmap.webp`,
  "Productivity Roadmap":             `${BASE}/productivity-roadmap.webp`,
  "Cloud Engineer Roadmap":           `${BASE}/cloud-engineer-roadmap.webp`,
  "AI Beginner Roadmap":              `${BASE}/ai-beginner-roadmap.webp`,
  "Claude Code":                      `${BASE}/claudecode-series.webp`,
  "Prompt Engineering":               `${BASE}/prompt-engineering.webp`,
  "RAG API":                          `${BASE}/orchard.webp`,
  "Ollama":                           `${BASE}/greenhouse.webp`,
  "DevOps Roadmap":                   `${BASE}/devops-roadmap.webp`,
  "DevSecOps Roadmap":                `${BASE}/devsecops-roadmap.webp`,
  "6 Day AWS DevOps Roadmap":         `${BASE}/6-day-devops-roadmap.webp`,
  "Security Engineer Roadmap":        `${BASE}/security-engr-roadmap.webp`,
  "Solutions Architect Roadmap":      `${BASE}/solutions-architect-roadmap.webp`,
  "AWS Beginner Roadmap":             `${BASE}/aws-beginner-roadmap.webp`,
  "AWS Cloud Practitioner Roadmap":   `${BASE}/aws-ccp-roadmap.webp`,
  "Networks":                         `${BASE}/beach.webp`,
  "All AI / ML":                      `${BASE}/mushroom.webp`,
  "AWS Bedrock":                      `${BASE}/potions.webp`,
  "Popular AI Tools":                 `${BASE}/flower-garden.webp`,
  "Model Context Protocol (MCP)":     `${BASE}/lake.webp`,
  "Cursor":                           `${BASE}/wellington-1.webp`,
  "n8n":                              `${BASE}/n8n-automation.webp`,
  "AI Security Scanners":             `${BASE}/night-sky.webp`,
  "Vercel":                           `${BASE}/finops-ai.webp`,
  "Kubernetes":                       `${BASE}/harbour.webp`,
  "Terraform":                        `${BASE}/infrastructure-automation.webp`,
  "Three-Tier":                       `${BASE}/sky-islands.webp`,
  "AWS Security Tools":               `${BASE}/cowboy-dessert.webp`,
  "Databases":                        `${BASE}/sandy-jungle.webp`,
  "Build with OpenClaw":              `${BASE}/shipwreck.webp`,
  "Account Management":               `${BASE}/swamp.webp`,
  "Amazon DynamoDB":                  `${BASE}/nosql.webp`,
  "Amazon EKS":                       `${BASE}/kubernetes-cloud.webp`,
  "Amazon Lex Chatbot":               `${BASE}/waterfall.webp`,
  "Amazon RDS":                       `${BASE}/database.webp`,
  "Amazon VPC":                       `${BASE}/fields-of-gold.webp`,
  "Archive":                          `${BASE}/dessert.webp`,
  "AWS Cloud Formation":              `${BASE}/infrastructure-code.webp`,
  "AWS CodeArtifact":                 `${BASE}/package-manager.webp`,
  "AWS CodeBuild":                    `${BASE}/build-automation.webp`,
  "AWS CodeDeploy":                   `${BASE}/deployment.webp`,
  "AWS CodePipeline":                 `${BASE}/pipeline.webp`,
  "AWS Lambda":                       `${BASE}/serverless.webp`,
  "AWS Secrets Manager":              `${BASE}/security.webp`,
  "Compute":                          `${BASE}/into-the-light.webp`,
  "Docker":                           `${BASE}/whale.webp`,
  "Storage":                          `${BASE}/cavern.webp`,
};

export function getCategoryImage(category: string): string {
  return CATEGORY_IMAGES[category] ?? `${BASE}/plane-isle.webp`;
}
